### ISSUE TITLE
Step 5 in Budyko Model WF fails

### ISSUE THREAD

**Issue by KittelC** [GlobWetlandAfrica/GWA_models_and_workflows#55]
I get the following error in the Clean streams and catchments step: 
" Error executing algorithm  'QgsVectorLayer' object has no attribute 'changeAttributeValues' See log for more details " 
The layer in question (the stream shapefile) is in editing mode when the wokflow crashes.

**Comment by radosuav** [comment]
This is probably due to older version of QGIS 2.18. changeAttributeValues [was added](https://github.com/qgis/QGIS/commit/140b40bc341d900abf5f8ed91cd4a4d5cc9e0de0#diff-106be592650b55ccae79c83eecd15ceb) in March 2018 so in older versions you will get this exception. 

@KittelC could you please update QGIS and other packages using the OSGeo4W setup utility. Also download the latest Processing code from the [TIGER-NET repository](https://github.com/TIGER-NET/WOIS_processing) and place it in C:\Users\user_name\.qgis2\python\plugins\processing.

This might also fix issue #54 but if not then I will investigate further.

**Comment by KittelC** [comment]
This issue was fixed by updating QGIS and the processing code - thank you!
